spring:
  main:
    web-application-type: none
    banner-mode: off
  shell:
    config:
      location: "{userconfig}/springcli"
    history:
      name: spring-cli-history.log
    command:
      completion:
        root-command: spring-cli
      version:
        show-git-short-commit-id: true
  cli:
    github:
      client-id: 10a18d1837ecdac59ba2
      default-scopes: repo,read:org
#    templateCatalogs:
#      - name: catalog1
#        description: The first catalog
#        url: https://github.com/rd-1-2022/template-catalog
#      - name: catalog2
#        description: The second catalog
#        url: https://github.com/rd-1-2022/template-catalog-2
#    templateRepositories:
#      - name: jpa
#        description: Learn how to work with JPA data persistence using Spring Data JPA.
#        url: https://github.com/rd-1-2022/rpt-spring-data-jpa
#        tags:
#          - jpa
#          - h2
    defaults:
      project-name: demo
#      package-name: com.xkcd
#      template-repository-name: jpa
## disable console logging
logging:
  pattern:
    console:
# log debug from a cli
#  file:
#    name: shell.log
#  level:
#    root: debug
#    org:
#      springframework:
#        up: debug
#        shell: debug
