spring:
  main:
    web-application-type: none
    banner-mode: off
  shell:
    config:
      location: "{userconfig}/springcli"
    history:
      name: spring-cli-history.log
    command:
      completion:
        root-command: spring
      version:
        show-git-short-commit-id: true
  cli:
    github:
      client-id: 10a18d1837ecdac59ba2
      default-scopes: repo,read:org

## disable console logging
logging:
  pattern:
#    console:
# log debug from a cli
  file:
    name: shell.log
  level:
    root: debug
    org:
      springframework:
        cli: debug
        shell: debug
