name: JR Assemble JavaArchive

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  assemble:
    runs-on: ubuntu-latest
    name: Assemble
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: Download fatjar
        uses: actions/download-artifact@v3
        with:
          name: fatjar
          path: build/libs

      - name: JR Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble --assembler javaArchive
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
      - uses: actions/upload-artifact@v3
        with:
          name: javaarchive
          path: out/jreleaser/assemble/spring-cli/java-archive/*.zip
          retention-days: 1
