name: Early Access

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  precheck:
    if: github.repository_owner == 'spring-projects-experimental' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/jr-version.yml
    with:
      version:
  build:
    needs: [precheck]
    uses: ./.github/workflows/jr-build.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
  javaarchive:
    needs: [precheck,build]
    uses: ./.github/workflows/jr-assemble-javaarchive.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  jlink:
    needs: [precheck,build]
    uses: ./.github/workflows/jr-assemble-jlink.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  jpackage:
    needs: [precheck,jlink]
    uses: ./.github/workflows/jr-assemble-jpackage.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  release:
    needs: [precheck,javaarchive,jpackage]
    uses: ./.github/workflows/jr-release.yml
    secrets: inherit
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}

